/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mocksocklib.h"

typedef struct _CMOCK_socklib_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;

} CMOCK_socklib_init_CALL_INSTANCE;

typedef struct _CMOCK_socklib_open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  HSOCKET* Expected_socket_handle;
  char* Expected_host;
  int Expected_port;
  char* Expected_if_name;
  int Expected_timeout;

} CMOCK_socklib_open_CALL_INSTANCE;

typedef struct _CMOCK_socklib_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HSOCKET* Expected_socket_handle;

} CMOCK_socklib_close_CALL_INSTANCE;

typedef struct _CMOCK_socklib_cleanup_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_socklib_cleanup_CALL_INSTANCE;

typedef struct _CMOCK_socklib_read_header_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  HSOCKET* Expected_socket_handle;
  char* Expected_buffer;
  int Expected_size;

} CMOCK_socklib_read_header_CALL_INSTANCE;

typedef struct _CMOCK_socklib_recvall_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  HSOCKET* Expected_socket_handle;
  char* Expected_buffer;
  int Expected_size;
  int Expected_timeout;

} CMOCK_socklib_recvall_CALL_INSTANCE;

typedef struct _CMOCK_socklib_sendall_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  HSOCKET* Expected_socket_handle;
  char* Expected_buffer;
  int Expected_size;

} CMOCK_socklib_sendall_CALL_INSTANCE;

typedef struct _CMOCK_read_interface_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  char* Expected_if_name;
  uint32_t* Expected_addr;

} CMOCK_read_interface_CALL_INSTANCE;

static struct MocksocklibInstance
{
  int socklib_init_IgnoreBool;
  error_code socklib_init_FinalReturn;
  CMOCK_socklib_init_CALLBACK socklib_init_CallbackFunctionPointer;
  int socklib_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE socklib_init_CallInstance;
  int socklib_open_IgnoreBool;
  error_code socklib_open_FinalReturn;
  CMOCK_socklib_open_CALLBACK socklib_open_CallbackFunctionPointer;
  int socklib_open_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE socklib_open_CallInstance;
  int socklib_close_IgnoreBool;
  CMOCK_socklib_close_CALLBACK socklib_close_CallbackFunctionPointer;
  int socklib_close_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE socklib_close_CallInstance;
  int socklib_cleanup_IgnoreBool;
  CMOCK_socklib_cleanup_CALLBACK socklib_cleanup_CallbackFunctionPointer;
  int socklib_cleanup_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE socklib_cleanup_CallInstance;
  int socklib_read_header_IgnoreBool;
  error_code socklib_read_header_FinalReturn;
  CMOCK_socklib_read_header_CALLBACK socklib_read_header_CallbackFunctionPointer;
  int socklib_read_header_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE socklib_read_header_CallInstance;
  int socklib_recvall_IgnoreBool;
  error_code socklib_recvall_FinalReturn;
  CMOCK_socklib_recvall_CALLBACK socklib_recvall_CallbackFunctionPointer;
  int socklib_recvall_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE socklib_recvall_CallInstance;
  int socklib_sendall_IgnoreBool;
  int socklib_sendall_FinalReturn;
  CMOCK_socklib_sendall_CALLBACK socklib_sendall_CallbackFunctionPointer;
  int socklib_sendall_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE socklib_sendall_CallInstance;
  int read_interface_IgnoreBool;
  error_code read_interface_FinalReturn;
  CMOCK_read_interface_CALLBACK read_interface_CallbackFunctionPointer;
  int read_interface_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE read_interface_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocksocklib_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.socklib_init_IgnoreBool)
    Mock.socklib_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.socklib_init_CallInstance, cmock_line, "Function 'socklib_init' called less times than expected.");
  if (Mock.socklib_init_CallbackFunctionPointer != NULL)
    Mock.socklib_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.socklib_open_IgnoreBool)
    Mock.socklib_open_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.socklib_open_CallInstance, cmock_line, "Function 'socklib_open' called less times than expected.");
  if (Mock.socklib_open_CallbackFunctionPointer != NULL)
    Mock.socklib_open_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.socklib_close_IgnoreBool)
    Mock.socklib_close_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.socklib_close_CallInstance, cmock_line, "Function 'socklib_close' called less times than expected.");
  if (Mock.socklib_close_CallbackFunctionPointer != NULL)
    Mock.socklib_close_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.socklib_cleanup_IgnoreBool)
    Mock.socklib_cleanup_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.socklib_cleanup_CallInstance, cmock_line, "Function 'socklib_cleanup' called less times than expected.");
  if (Mock.socklib_cleanup_CallbackFunctionPointer != NULL)
    Mock.socklib_cleanup_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.socklib_read_header_IgnoreBool)
    Mock.socklib_read_header_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.socklib_read_header_CallInstance, cmock_line, "Function 'socklib_read_header' called less times than expected.");
  if (Mock.socklib_read_header_CallbackFunctionPointer != NULL)
    Mock.socklib_read_header_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.socklib_recvall_IgnoreBool)
    Mock.socklib_recvall_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.socklib_recvall_CallInstance, cmock_line, "Function 'socklib_recvall' called less times than expected.");
  if (Mock.socklib_recvall_CallbackFunctionPointer != NULL)
    Mock.socklib_recvall_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.socklib_sendall_IgnoreBool)
    Mock.socklib_sendall_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.socklib_sendall_CallInstance, cmock_line, "Function 'socklib_sendall' called less times than expected.");
  if (Mock.socklib_sendall_CallbackFunctionPointer != NULL)
    Mock.socklib_sendall_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.read_interface_IgnoreBool)
    Mock.read_interface_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.read_interface_CallInstance, cmock_line, "Function 'read_interface' called less times than expected.");
  if (Mock.read_interface_CallbackFunctionPointer != NULL)
    Mock.read_interface_CallInstance = CMOCK_GUTS_NONE;
}

void Mocksocklib_Init(void)
{
  Mocksocklib_Destroy();
}

void Mocksocklib_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.socklib_init_CallbackFunctionPointer = NULL;
  Mock.socklib_init_CallbackCalls = 0;
  Mock.socklib_open_CallbackFunctionPointer = NULL;
  Mock.socklib_open_CallbackCalls = 0;
  Mock.socklib_close_CallbackFunctionPointer = NULL;
  Mock.socklib_close_CallbackCalls = 0;
  Mock.socklib_cleanup_CallbackFunctionPointer = NULL;
  Mock.socklib_cleanup_CallbackCalls = 0;
  Mock.socklib_read_header_CallbackFunctionPointer = NULL;
  Mock.socklib_read_header_CallbackCalls = 0;
  Mock.socklib_recvall_CallbackFunctionPointer = NULL;
  Mock.socklib_recvall_CallbackCalls = 0;
  Mock.socklib_sendall_CallbackFunctionPointer = NULL;
  Mock.socklib_sendall_CallbackCalls = 0;
  Mock.read_interface_CallbackFunctionPointer = NULL;
  Mock.read_interface_CallbackCalls = 0;
}

error_code socklib_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_socklib_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.socklib_init_CallInstance);
  Mock.socklib_init_CallInstance = CMock_Guts_MemNext(Mock.socklib_init_CallInstance);
  if (Mock.socklib_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.socklib_init_FinalReturn;
    memcpy(&Mock.socklib_init_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.socklib_init_CallbackFunctionPointer != NULL)
  {
    return Mock.socklib_init_CallbackFunctionPointer(Mock.socklib_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'socklib_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void socklib_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_init_CALL_INSTANCE));
  CMOCK_socklib_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_init_CallInstance = CMock_Guts_MemChain(Mock.socklib_init_CallInstance, cmock_guts_index);
  Mock.socklib_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.socklib_init_IgnoreBool = (int)1;
}

void socklib_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_init_CALL_INSTANCE));
  CMOCK_socklib_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_init_CallInstance = CMock_Guts_MemChain(Mock.socklib_init_CallInstance, cmock_guts_index);
  Mock.socklib_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void socklib_init_StubWithCallback(CMOCK_socklib_init_CALLBACK Callback)
{
  Mock.socklib_init_CallbackFunctionPointer = Callback;
}

error_code socklib_open(HSOCKET* socket_handle, char* host, int port, char* if_name, int timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_socklib_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.socklib_open_CallInstance);
  Mock.socklib_open_CallInstance = CMock_Guts_MemNext(Mock.socklib_open_CallInstance);
  if (Mock.socklib_open_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.socklib_open_FinalReturn;
    memcpy(&Mock.socklib_open_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.socklib_open_CallbackFunctionPointer != NULL)
  {
    return Mock.socklib_open_CallbackFunctionPointer(socket_handle, host, port, if_name, timeout, Mock.socklib_open_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'socklib_open' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_socket_handle), (void*)(socket_handle), sizeof(HSOCKET), cmock_line, "Function 'socklib_open' called with unexpected value for argument 'socket_handle'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_host, host, cmock_line, "Function 'socklib_open' called with unexpected value for argument 'host'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_port, port, cmock_line, "Function 'socklib_open' called with unexpected value for argument 'port'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_if_name, if_name, cmock_line, "Function 'socklib_open' called with unexpected value for argument 'if_name'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_timeout, timeout, cmock_line, "Function 'socklib_open' called with unexpected value for argument 'timeout'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_socklib_open(CMOCK_socklib_open_CALL_INSTANCE* cmock_call_instance, HSOCKET* socket_handle, char* host, int port, char* if_name, int timeout)
{
  cmock_call_instance->Expected_socket_handle = socket_handle;
  cmock_call_instance->Expected_host = host;
  cmock_call_instance->Expected_port = port;
  cmock_call_instance->Expected_if_name = if_name;
  cmock_call_instance->Expected_timeout = timeout;
}

void socklib_open_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_open_CALL_INSTANCE));
  CMOCK_socklib_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_open_CallInstance = CMock_Guts_MemChain(Mock.socklib_open_CallInstance, cmock_guts_index);
  Mock.socklib_open_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.socklib_open_IgnoreBool = (int)1;
}

void socklib_open_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HSOCKET* socket_handle, char* host, int port, char* if_name, int timeout, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_open_CALL_INSTANCE));
  CMOCK_socklib_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_open_CallInstance = CMock_Guts_MemChain(Mock.socklib_open_CallInstance, cmock_guts_index);
  Mock.socklib_open_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_socklib_open(cmock_call_instance, socket_handle, host, port, if_name, timeout);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void socklib_open_StubWithCallback(CMOCK_socklib_open_CALLBACK Callback)
{
  Mock.socklib_open_CallbackFunctionPointer = Callback;
}

void socklib_close(HSOCKET* socket_handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_socklib_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.socklib_close_CallInstance);
  Mock.socklib_close_CallInstance = CMock_Guts_MemNext(Mock.socklib_close_CallInstance);
  if (Mock.socklib_close_IgnoreBool)
  {
    return;
  }
  if (Mock.socklib_close_CallbackFunctionPointer != NULL)
  {
    Mock.socklib_close_CallbackFunctionPointer(socket_handle, Mock.socklib_close_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'socklib_close' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_socket_handle), (void*)(socket_handle), sizeof(HSOCKET), cmock_line, "Function 'socklib_close' called with unexpected value for argument 'socket_handle'.");
  }
}

void CMockExpectParameters_socklib_close(CMOCK_socklib_close_CALL_INSTANCE* cmock_call_instance, HSOCKET* socket_handle)
{
  cmock_call_instance->Expected_socket_handle = socket_handle;
}

void socklib_close_CMockIgnore(void)
{
  Mock.socklib_close_IgnoreBool = (int)1;
}

void socklib_close_CMockExpect(UNITY_LINE_TYPE cmock_line, HSOCKET* socket_handle)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_close_CALL_INSTANCE));
  CMOCK_socklib_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_close_CallInstance = CMock_Guts_MemChain(Mock.socklib_close_CallInstance, cmock_guts_index);
  Mock.socklib_close_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_socklib_close(cmock_call_instance, socket_handle);
}

void socklib_close_StubWithCallback(CMOCK_socklib_close_CALLBACK Callback)
{
  Mock.socklib_close_CallbackFunctionPointer = Callback;
}

void socklib_cleanup(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_socklib_cleanup_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_cleanup_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.socklib_cleanup_CallInstance);
  Mock.socklib_cleanup_CallInstance = CMock_Guts_MemNext(Mock.socklib_cleanup_CallInstance);
  if (Mock.socklib_cleanup_IgnoreBool)
  {
    return;
  }
  if (Mock.socklib_cleanup_CallbackFunctionPointer != NULL)
  {
    Mock.socklib_cleanup_CallbackFunctionPointer(Mock.socklib_cleanup_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'socklib_cleanup' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void socklib_cleanup_CMockIgnore(void)
{
  Mock.socklib_cleanup_IgnoreBool = (int)1;
}

void socklib_cleanup_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_cleanup_CALL_INSTANCE));
  CMOCK_socklib_cleanup_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_cleanup_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_cleanup_CallInstance = CMock_Guts_MemChain(Mock.socklib_cleanup_CallInstance, cmock_guts_index);
  Mock.socklib_cleanup_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void socklib_cleanup_StubWithCallback(CMOCK_socklib_cleanup_CALLBACK Callback)
{
  Mock.socklib_cleanup_CallbackFunctionPointer = Callback;
}

error_code socklib_read_header(RIP_MANAGER_INFO* rmi, HSOCKET* socket_handle, char* buffer, int size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_socklib_read_header_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_read_header_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.socklib_read_header_CallInstance);
  Mock.socklib_read_header_CallInstance = CMock_Guts_MemNext(Mock.socklib_read_header_CallInstance);
  if (Mock.socklib_read_header_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.socklib_read_header_FinalReturn;
    memcpy(&Mock.socklib_read_header_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.socklib_read_header_CallbackFunctionPointer != NULL)
  {
    return Mock.socklib_read_header_CallbackFunctionPointer(rmi, socket_handle, buffer, size, Mock.socklib_read_header_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'socklib_read_header' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'socklib_read_header' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_socket_handle), (void*)(socket_handle), sizeof(HSOCKET), cmock_line, "Function 'socklib_read_header' called with unexpected value for argument 'socket_handle'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, "Function 'socklib_read_header' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_size, size, cmock_line, "Function 'socklib_read_header' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_socklib_read_header(CMOCK_socklib_read_header_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, HSOCKET* socket_handle, char* buffer, int size)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_socket_handle = socket_handle;
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_size = size;
}

void socklib_read_header_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_read_header_CALL_INSTANCE));
  CMOCK_socklib_read_header_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_read_header_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_read_header_CallInstance = CMock_Guts_MemChain(Mock.socklib_read_header_CallInstance, cmock_guts_index);
  Mock.socklib_read_header_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.socklib_read_header_IgnoreBool = (int)1;
}

void socklib_read_header_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, HSOCKET* socket_handle, char* buffer, int size, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_read_header_CALL_INSTANCE));
  CMOCK_socklib_read_header_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_read_header_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_read_header_CallInstance = CMock_Guts_MemChain(Mock.socklib_read_header_CallInstance, cmock_guts_index);
  Mock.socklib_read_header_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_socklib_read_header(cmock_call_instance, rmi, socket_handle, buffer, size);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void socklib_read_header_StubWithCallback(CMOCK_socklib_read_header_CALLBACK Callback)
{
  Mock.socklib_read_header_CallbackFunctionPointer = Callback;
}

error_code socklib_recvall(RIP_MANAGER_INFO* rmi, HSOCKET* socket_handle, char* buffer, int size, int timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_socklib_recvall_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_recvall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.socklib_recvall_CallInstance);
  Mock.socklib_recvall_CallInstance = CMock_Guts_MemNext(Mock.socklib_recvall_CallInstance);
  if (Mock.socklib_recvall_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.socklib_recvall_FinalReturn;
    memcpy(&Mock.socklib_recvall_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.socklib_recvall_CallbackFunctionPointer != NULL)
  {
    return Mock.socklib_recvall_CallbackFunctionPointer(rmi, socket_handle, buffer, size, timeout, Mock.socklib_recvall_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'socklib_recvall' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'socklib_recvall' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_socket_handle), (void*)(socket_handle), sizeof(HSOCKET), cmock_line, "Function 'socklib_recvall' called with unexpected value for argument 'socket_handle'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, "Function 'socklib_recvall' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_size, size, cmock_line, "Function 'socklib_recvall' called with unexpected value for argument 'size'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_timeout, timeout, cmock_line, "Function 'socklib_recvall' called with unexpected value for argument 'timeout'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_socklib_recvall(CMOCK_socklib_recvall_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, HSOCKET* socket_handle, char* buffer, int size, int timeout)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_socket_handle = socket_handle;
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_size = size;
  cmock_call_instance->Expected_timeout = timeout;
}

void socklib_recvall_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_recvall_CALL_INSTANCE));
  CMOCK_socklib_recvall_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_recvall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_recvall_CallInstance = CMock_Guts_MemChain(Mock.socklib_recvall_CallInstance, cmock_guts_index);
  Mock.socklib_recvall_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.socklib_recvall_IgnoreBool = (int)1;
}

void socklib_recvall_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, HSOCKET* socket_handle, char* buffer, int size, int timeout, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_recvall_CALL_INSTANCE));
  CMOCK_socklib_recvall_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_recvall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_recvall_CallInstance = CMock_Guts_MemChain(Mock.socklib_recvall_CallInstance, cmock_guts_index);
  Mock.socklib_recvall_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_socklib_recvall(cmock_call_instance, rmi, socket_handle, buffer, size, timeout);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void socklib_recvall_StubWithCallback(CMOCK_socklib_recvall_CALLBACK Callback)
{
  Mock.socklib_recvall_CallbackFunctionPointer = Callback;
}

int socklib_sendall(HSOCKET* socket_handle, char* buffer, int size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_socklib_sendall_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_sendall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.socklib_sendall_CallInstance);
  Mock.socklib_sendall_CallInstance = CMock_Guts_MemNext(Mock.socklib_sendall_CallInstance);
  if (Mock.socklib_sendall_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.socklib_sendall_FinalReturn;
    Mock.socklib_sendall_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.socklib_sendall_CallbackFunctionPointer != NULL)
  {
    return Mock.socklib_sendall_CallbackFunctionPointer(socket_handle, buffer, size, Mock.socklib_sendall_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'socklib_sendall' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_socket_handle), (void*)(socket_handle), sizeof(HSOCKET), cmock_line, "Function 'socklib_sendall' called with unexpected value for argument 'socket_handle'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, "Function 'socklib_sendall' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_size, size, cmock_line, "Function 'socklib_sendall' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_socklib_sendall(CMOCK_socklib_sendall_CALL_INSTANCE* cmock_call_instance, HSOCKET* socket_handle, char* buffer, int size)
{
  cmock_call_instance->Expected_socket_handle = socket_handle;
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_size = size;
}

void socklib_sendall_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_sendall_CALL_INSTANCE));
  CMOCK_socklib_sendall_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_sendall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_sendall_CallInstance = CMock_Guts_MemChain(Mock.socklib_sendall_CallInstance, cmock_guts_index);
  Mock.socklib_sendall_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.socklib_sendall_IgnoreBool = (int)1;
}

void socklib_sendall_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HSOCKET* socket_handle, char* buffer, int size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_socklib_sendall_CALL_INSTANCE));
  CMOCK_socklib_sendall_CALL_INSTANCE* cmock_call_instance = (CMOCK_socklib_sendall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.socklib_sendall_CallInstance = CMock_Guts_MemChain(Mock.socklib_sendall_CallInstance, cmock_guts_index);
  Mock.socklib_sendall_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_socklib_sendall(cmock_call_instance, socket_handle, buffer, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void socklib_sendall_StubWithCallback(CMOCK_socklib_sendall_CALLBACK Callback)
{
  Mock.socklib_sendall_CallbackFunctionPointer = Callback;
}

error_code read_interface(char* if_name, uint32_t* addr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_read_interface_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_interface_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.read_interface_CallInstance);
  Mock.read_interface_CallInstance = CMock_Guts_MemNext(Mock.read_interface_CallInstance);
  if (Mock.read_interface_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.read_interface_FinalReturn;
    memcpy(&Mock.read_interface_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.read_interface_CallbackFunctionPointer != NULL)
  {
    return Mock.read_interface_CallbackFunctionPointer(if_name, addr, Mock.read_interface_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'read_interface' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_if_name, if_name, cmock_line, "Function 'read_interface' called with unexpected value for argument 'if_name'.");
  }
  {
    if (cmock_call_instance->Expected_addr == NULL)
      { UNITY_TEST_ASSERT_NULL(addr, cmock_line, "Expected NULL. Function 'read_interface' called with unexpected value for argument 'addr'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_addr, addr, 1, cmock_line, "Function 'read_interface' called with unexpected value for argument 'addr'."); }
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_read_interface(CMOCK_read_interface_CALL_INSTANCE* cmock_call_instance, char* if_name, uint32_t* addr)
{
  cmock_call_instance->Expected_if_name = if_name;
  cmock_call_instance->Expected_addr = addr;
}

void read_interface_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_interface_CALL_INSTANCE));
  CMOCK_read_interface_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_interface_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_interface_CallInstance = CMock_Guts_MemChain(Mock.read_interface_CallInstance, cmock_guts_index);
  Mock.read_interface_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.read_interface_IgnoreBool = (int)1;
}

void read_interface_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* if_name, uint32_t* addr, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_interface_CALL_INSTANCE));
  CMOCK_read_interface_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_interface_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_interface_CallInstance = CMock_Guts_MemChain(Mock.read_interface_CallInstance, cmock_guts_index);
  Mock.read_interface_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_read_interface(cmock_call_instance, if_name, addr);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void read_interface_StubWithCallback(CMOCK_read_interface_CALLBACK Callback)
{
  Mock.read_interface_CallbackFunctionPointer = Callback;
}

