/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockdebug.h"

typedef struct _CMOCK_debug_open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debug_open_CALL_INSTANCE;

typedef struct _CMOCK_debug_set_filename_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_filename;

} CMOCK_debug_set_filename_CALL_INSTANCE;

typedef struct _CMOCK_debug_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debug_close_CALL_INSTANCE;

typedef struct _CMOCK_debug_printf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_fmt;

} CMOCK_debug_printf_CALL_INSTANCE;

typedef struct _CMOCK_debug_enable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debug_enable_CALL_INSTANCE;

typedef struct _CMOCK_debug_print_error_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debug_print_error_CALL_INSTANCE;

static struct MockdebugInstance
{
  int debug_open_IgnoreBool;
  CMOCK_debug_open_CALLBACK debug_open_CallbackFunctionPointer;
  int debug_open_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE debug_open_CallInstance;
  int debug_set_filename_IgnoreBool;
  CMOCK_debug_set_filename_CALLBACK debug_set_filename_CallbackFunctionPointer;
  int debug_set_filename_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE debug_set_filename_CallInstance;
  int debug_close_IgnoreBool;
  CMOCK_debug_close_CALLBACK debug_close_CallbackFunctionPointer;
  int debug_close_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE debug_close_CallInstance;
  int debug_printf_IgnoreBool;
  CMOCK_debug_printf_CALLBACK debug_printf_CallbackFunctionPointer;
  int debug_printf_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE debug_printf_CallInstance;
  int debug_enable_IgnoreBool;
  CMOCK_debug_enable_CALLBACK debug_enable_CallbackFunctionPointer;
  int debug_enable_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE debug_enable_CallInstance;
  int debug_print_error_IgnoreBool;
  CMOCK_debug_print_error_CALLBACK debug_print_error_CallbackFunctionPointer;
  int debug_print_error_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE debug_print_error_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockdebug_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.debug_open_IgnoreBool)
    Mock.debug_open_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debug_open_CallInstance, cmock_line, "Function 'debug_open' called less times than expected.");
  if (Mock.debug_open_CallbackFunctionPointer != NULL)
    Mock.debug_open_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.debug_set_filename_IgnoreBool)
    Mock.debug_set_filename_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debug_set_filename_CallInstance, cmock_line, "Function 'debug_set_filename' called less times than expected.");
  if (Mock.debug_set_filename_CallbackFunctionPointer != NULL)
    Mock.debug_set_filename_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.debug_close_IgnoreBool)
    Mock.debug_close_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debug_close_CallInstance, cmock_line, "Function 'debug_close' called less times than expected.");
  if (Mock.debug_close_CallbackFunctionPointer != NULL)
    Mock.debug_close_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.debug_printf_IgnoreBool)
    Mock.debug_printf_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debug_printf_CallInstance, cmock_line, "Function 'debug_printf' called less times than expected.");
  if (Mock.debug_printf_CallbackFunctionPointer != NULL)
    Mock.debug_printf_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.debug_enable_IgnoreBool)
    Mock.debug_enable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debug_enable_CallInstance, cmock_line, "Function 'debug_enable' called less times than expected.");
  if (Mock.debug_enable_CallbackFunctionPointer != NULL)
    Mock.debug_enable_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.debug_print_error_IgnoreBool)
    Mock.debug_print_error_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debug_print_error_CallInstance, cmock_line, "Function 'debug_print_error' called less times than expected.");
  if (Mock.debug_print_error_CallbackFunctionPointer != NULL)
    Mock.debug_print_error_CallInstance = CMOCK_GUTS_NONE;
}

void Mockdebug_Init(void)
{
  Mockdebug_Destroy();
}

void Mockdebug_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.debug_open_CallbackFunctionPointer = NULL;
  Mock.debug_open_CallbackCalls = 0;
  Mock.debug_set_filename_CallbackFunctionPointer = NULL;
  Mock.debug_set_filename_CallbackCalls = 0;
  Mock.debug_close_CallbackFunctionPointer = NULL;
  Mock.debug_close_CallbackCalls = 0;
  Mock.debug_printf_CallbackFunctionPointer = NULL;
  Mock.debug_printf_CallbackCalls = 0;
  Mock.debug_enable_CallbackFunctionPointer = NULL;
  Mock.debug_enable_CallbackCalls = 0;
  Mock.debug_print_error_CallbackFunctionPointer = NULL;
  Mock.debug_print_error_CallbackCalls = 0;
}

void debug_open(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debug_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debug_open_CallInstance);
  Mock.debug_open_CallInstance = CMock_Guts_MemNext(Mock.debug_open_CallInstance);
  if (Mock.debug_open_IgnoreBool)
  {
    return;
  }
  if (Mock.debug_open_CallbackFunctionPointer != NULL)
  {
    Mock.debug_open_CallbackFunctionPointer(Mock.debug_open_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'debug_open' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void debug_open_CMockIgnore(void)
{
  Mock.debug_open_IgnoreBool = (int)1;
}

void debug_open_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debug_open_CALL_INSTANCE));
  CMOCK_debug_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debug_open_CallInstance = CMock_Guts_MemChain(Mock.debug_open_CallInstance, cmock_guts_index);
  Mock.debug_open_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void debug_open_StubWithCallback(CMOCK_debug_open_CALLBACK Callback)
{
  Mock.debug_open_CallbackFunctionPointer = Callback;
}

void debug_set_filename(char* filename)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debug_set_filename_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_set_filename_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debug_set_filename_CallInstance);
  Mock.debug_set_filename_CallInstance = CMock_Guts_MemNext(Mock.debug_set_filename_CallInstance);
  if (Mock.debug_set_filename_IgnoreBool)
  {
    return;
  }
  if (Mock.debug_set_filename_CallbackFunctionPointer != NULL)
  {
    Mock.debug_set_filename_CallbackFunctionPointer(filename, Mock.debug_set_filename_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'debug_set_filename' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_filename, filename, cmock_line, "Function 'debug_set_filename' called with unexpected value for argument 'filename'.");
  }
}

void CMockExpectParameters_debug_set_filename(CMOCK_debug_set_filename_CALL_INSTANCE* cmock_call_instance, char* filename)
{
  cmock_call_instance->Expected_filename = filename;
}

void debug_set_filename_CMockIgnore(void)
{
  Mock.debug_set_filename_IgnoreBool = (int)1;
}

void debug_set_filename_CMockExpect(UNITY_LINE_TYPE cmock_line, char* filename)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debug_set_filename_CALL_INSTANCE));
  CMOCK_debug_set_filename_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_set_filename_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debug_set_filename_CallInstance = CMock_Guts_MemChain(Mock.debug_set_filename_CallInstance, cmock_guts_index);
  Mock.debug_set_filename_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debug_set_filename(cmock_call_instance, filename);
}

void debug_set_filename_StubWithCallback(CMOCK_debug_set_filename_CALLBACK Callback)
{
  Mock.debug_set_filename_CallbackFunctionPointer = Callback;
}

void debug_close(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debug_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debug_close_CallInstance);
  Mock.debug_close_CallInstance = CMock_Guts_MemNext(Mock.debug_close_CallInstance);
  if (Mock.debug_close_IgnoreBool)
  {
    return;
  }
  if (Mock.debug_close_CallbackFunctionPointer != NULL)
  {
    Mock.debug_close_CallbackFunctionPointer(Mock.debug_close_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'debug_close' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void debug_close_CMockIgnore(void)
{
  Mock.debug_close_IgnoreBool = (int)1;
}

void debug_close_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debug_close_CALL_INSTANCE));
  CMOCK_debug_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debug_close_CallInstance = CMock_Guts_MemChain(Mock.debug_close_CallInstance, cmock_guts_index);
  Mock.debug_close_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void debug_close_StubWithCallback(CMOCK_debug_close_CALLBACK Callback)
{
  Mock.debug_close_CallbackFunctionPointer = Callback;
}

void debug_printf(char* fmt, ...)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debug_printf_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debug_printf_CallInstance);
  Mock.debug_printf_CallInstance = CMock_Guts_MemNext(Mock.debug_printf_CallInstance);
  if (Mock.debug_printf_IgnoreBool)
  {
    return;
  }
  if (Mock.debug_printf_CallbackFunctionPointer != NULL)
  {
    Mock.debug_printf_CallbackFunctionPointer(fmt, Mock.debug_printf_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'debug_printf' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_fmt, fmt, cmock_line, "Function 'debug_printf' called with unexpected value for argument 'fmt'.");
  }
}

void CMockExpectParameters_debug_printf(CMOCK_debug_printf_CALL_INSTANCE* cmock_call_instance, char* fmt)
{
  cmock_call_instance->Expected_fmt = fmt;
}

void debug_printf_CMockIgnore(void)
{
  Mock.debug_printf_IgnoreBool = (int)1;
}

void debug_printf_CMockExpect(UNITY_LINE_TYPE cmock_line, char* fmt)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debug_printf_CALL_INSTANCE));
  CMOCK_debug_printf_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_printf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debug_printf_CallInstance = CMock_Guts_MemChain(Mock.debug_printf_CallInstance, cmock_guts_index);
  Mock.debug_printf_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debug_printf(cmock_call_instance, fmt);
}

void debug_printf_StubWithCallback(CMOCK_debug_printf_CALLBACK Callback)
{
  Mock.debug_printf_CallbackFunctionPointer = Callback;
}

void debug_enable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debug_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debug_enable_CallInstance);
  Mock.debug_enable_CallInstance = CMock_Guts_MemNext(Mock.debug_enable_CallInstance);
  if (Mock.debug_enable_IgnoreBool)
  {
    return;
  }
  if (Mock.debug_enable_CallbackFunctionPointer != NULL)
  {
    Mock.debug_enable_CallbackFunctionPointer(Mock.debug_enable_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'debug_enable' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void debug_enable_CMockIgnore(void)
{
  Mock.debug_enable_IgnoreBool = (int)1;
}

void debug_enable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debug_enable_CALL_INSTANCE));
  CMOCK_debug_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debug_enable_CallInstance = CMock_Guts_MemChain(Mock.debug_enable_CallInstance, cmock_guts_index);
  Mock.debug_enable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void debug_enable_StubWithCallback(CMOCK_debug_enable_CALLBACK Callback)
{
  Mock.debug_enable_CallbackFunctionPointer = Callback;
}

void debug_print_error(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debug_print_error_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_print_error_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debug_print_error_CallInstance);
  Mock.debug_print_error_CallInstance = CMock_Guts_MemNext(Mock.debug_print_error_CallInstance);
  if (Mock.debug_print_error_IgnoreBool)
  {
    return;
  }
  if (Mock.debug_print_error_CallbackFunctionPointer != NULL)
  {
    Mock.debug_print_error_CallbackFunctionPointer(Mock.debug_print_error_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'debug_print_error' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void debug_print_error_CMockIgnore(void)
{
  Mock.debug_print_error_IgnoreBool = (int)1;
}

void debug_print_error_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debug_print_error_CALL_INSTANCE));
  CMOCK_debug_print_error_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_print_error_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debug_print_error_CallInstance = CMock_Guts_MemChain(Mock.debug_print_error_CallInstance, cmock_guts_index);
  Mock.debug_print_error_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void debug_print_error_StubWithCallback(CMOCK_debug_print_error_CALLBACK Callback)
{
  Mock.debug_print_error_CallbackFunctionPointer = Callback;
}

