/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDEBUG_H
#define _MOCKDEBUG_H

#include "debug.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockdebug_Init(void);
void Mockdebug_Destroy(void);
void Mockdebug_Verify(void);




#define debug_open_Ignore() debug_open_CMockIgnore()
void debug_open_CMockIgnore(void);
#define debug_open_Expect() debug_open_CMockExpect(__LINE__)
void debug_open_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_debug_open_CALLBACK)(int cmock_num_calls);
void debug_open_StubWithCallback(CMOCK_debug_open_CALLBACK Callback);
#define debug_set_filename_Ignore() debug_set_filename_CMockIgnore()
void debug_set_filename_CMockIgnore(void);
#define debug_set_filename_Expect(filename) debug_set_filename_CMockExpect(__LINE__, filename)
void debug_set_filename_CMockExpect(UNITY_LINE_TYPE cmock_line, char* filename);
typedef void (* CMOCK_debug_set_filename_CALLBACK)(char* filename, int cmock_num_calls);
void debug_set_filename_StubWithCallback(CMOCK_debug_set_filename_CALLBACK Callback);
#define debug_close_Ignore() debug_close_CMockIgnore()
void debug_close_CMockIgnore(void);
#define debug_close_Expect() debug_close_CMockExpect(__LINE__)
void debug_close_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_debug_close_CALLBACK)(int cmock_num_calls);
void debug_close_StubWithCallback(CMOCK_debug_close_CALLBACK Callback);
#define debug_printf_Ignore() debug_printf_CMockIgnore()
void debug_printf_CMockIgnore(void);
#define debug_printf_Expect(fmt) debug_printf_CMockExpect(__LINE__, fmt)
void debug_printf_CMockExpect(UNITY_LINE_TYPE cmock_line, char* fmt);
typedef void (* CMOCK_debug_printf_CALLBACK)(char* fmt, int cmock_num_calls);
void debug_printf_StubWithCallback(CMOCK_debug_printf_CALLBACK Callback);
#define debug_enable_Ignore() debug_enable_CMockIgnore()
void debug_enable_CMockIgnore(void);
#define debug_enable_Expect() debug_enable_CMockExpect(__LINE__)
void debug_enable_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_debug_enable_CALLBACK)(int cmock_num_calls);
void debug_enable_StubWithCallback(CMOCK_debug_enable_CALLBACK Callback);
#define debug_print_error_Ignore() debug_print_error_CMockIgnore()
void debug_print_error_CMockIgnore(void);
#define debug_print_error_Expect() debug_print_error_CMockExpect(__LINE__)
void debug_print_error_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_debug_print_error_CALLBACK)(int cmock_num_calls);
void debug_print_error_StubWithCallback(CMOCK_debug_print_error_CALLBACK Callback);

#endif
